<?php

namespace Jdiassdev\LaravelTypesGen\Generators;

class TypeScriptGenerator
{
  public function generate(array $data): string
  {
    $output = "/** Auto-generated by LaravelTypesGen */\n\n";

    foreach ($data as $className => $fields) {

      $output .= "export interface {$className} {\n";

      foreach ($fields as $field => $type) {
        $output .= "  {$field}: {$type};\n";
      }

      $output .= "}\n\n";
    }

    return $output;
  }
}
