<?php

namespace Jdiassdev\LaravelTypesGen\Generators;

class TypeScriptGenerator
{
    public function generate(array $data): string
    {
        $output = "/** auto-generated by laraveltypesgen */\n\n";

        foreach ($data as $className => $fields) {
            $tree = $this->buildTree($fields);
            $output .= "export interface {$className} {\n";
            $output .= $this->renderFields($tree);
            $output .= "}\n\n";
        }

        return $output;
    }

    private function buildTree(array $fields): array
    {
        $tree = [];

        foreach ($fields as $path => $def) {
            $segments = explode('.', $path);

            if (count($segments) === 1) {
                $tree[$path] = $def + ['children' => null, 'is_array' => false];
                continue;
            }

            $this->insertNode($tree, $segments, $def);
        }

        return $tree;
    }

    private function insertNode(array &$tree, array $segments, array $def): void
    {
        $key = array_shift($segments);
        $isArray = isset($segments[0]) && $segments[0] === '*';

        if ($isArray) {
            array_shift($segments);
        }

        if (!isset($tree[$key])) {
            $tree[$key] = [
                'type' => $isArray ? 'array' : 'object',
                'optional' => false,
                'children' => [],
                'is_array' => $isArray,
            ];
        }

        if (empty($segments)) {
            return;
        }

        if (count($segments) === 1) {
            $tree[$key]['children'][$segments[0]] = $def + ['children' => null, 'is_array' => false];
        } else {
            $this->insertNode($tree[$key]['children'], $segments, $def);
        }
    }

    private function renderFields(array $fields, int $indent = 2): string
    {
        $output = '';
        $pad = str_repeat(' ', $indent);

        foreach ($fields as $field => $def) {
            $optional = $def['optional'] ? '?' : '';

            if ($def['children'] === null) {
                $output .= "{$pad}{$field}{$optional}: {$def['type']};\n";
            } elseif ($def['is_array']) {
                $output .= "{$pad}{$field}{$optional}: {\n";
                $output .= $this->renderFields($def['children'], $indent + 2);
                $output .= "{$pad}}[];\n";
            } else {
                $output .= "{$pad}{$field}{$optional}: {\n";
                $output .= $this->renderFields($def['children'], $indent + 2);
                $output .= "{$pad}};\n";
            }
        }

        return $output;
    }
}
